version: '3.8'

services:
  craveconnect-backend:
    image: arjunsaxena/craveconnect-backend:latest
    container_name: craveconnect-backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend/uploads:/app/backend/uploads
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 